server:
  port: 10010
logging:
  level:
    org.lw: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  redis:
    host: 192.168.122.129
    port: 6379
    database: 0
    timeout: 5000ms
  application:
    name: gateway
  datasource:
    url: jdbc:postgresql://192.168.122.129:5432/dhongli
    driverClassName: org.postgresql.Driver
    username: dhongli
    password: 7355608
  boot:
    admin:
      client:
        enabled: true
        # spring-boot-admin 服务端地址
        url: http://localhost:8090
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      redis-route-definition-repository:
        enabled: true
    nacos:
      server-addr: 192.168.122.129:8848

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'




